-- MySQL Script generated by MySQL Workbench
-- Fri Jan 11 23:12:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taxi_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taxi_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxi_management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `taxi_management` ;

-- -----------------------------------------------------
-- Table `taxi_management`.`app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi_management`.`app` (
  `payment_method` VARCHAR(20) NULL DEFAULT NULL,
  `custid` INT(20) NOT NULL AUTO_INCREMENT,
  `car_no` VARCHAR(20) NULL DEFAULT NULL,
  `car_type` VARCHAR(20) NULL DEFAULT NULL,
  `amount` INT(20) NULL DEFAULT NULL,
  `route` INT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`custid`),
  INDEX `car_no` (`car_no` ASC) VISIBLE,
  CONSTRAINT `app_ibfk_1`
    FOREIGN KEY (`car_no`)
    REFERENCES `taxi_management`.`taxi` (`car_no`),
  CONSTRAINT `app_ibfk_2`
    FOREIGN KEY (`custid`)
    REFERENCES `taxi_management`.`customer` (`custid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taxi_management`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi_management`.`customer` (
  `customer_name` VARCHAR(30) NULL DEFAULT NULL,
  `custid` INT(20) NOT NULL AUTO_INCREMENT,
  `customer_rating` INT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`custid`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taxi_management`.`taxi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi_management`.`taxi` (
  `car_no` VARCHAR(20) NOT NULL,
  `driver_name` VARCHAR(20) NULL DEFAULT NULL,
  `rating` INT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`car_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
